name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Ensuring .NET 8.0 SDK is used

      - name: Build the application
        run: |
          cd DataBaseWebAPI # Navigate to the directory containing the solution file
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o output # Publish the application

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload' # Define the deployment action
          app_location: "/"
          api_location: "output/wwwroot" # Adjust if needed
          output_location: "output"
